###############################################################################
# CHARGING - Profiles
#
# Valid profile range: 300 - 399
###############################################################################

profiles:
  - profile:
      id: 300
      processes: []

  - profile:
      id: 301
      processes: []
