###############################################################################
# FAULT - Profiles
#
# Valid profile range: 400 - 499
###############################################################################

profiles:
  - profile:
      id: 400
      processes: []

  - profile:
      id: 401
      processes: []
